datasource:
  default: ${APP_ENV}

  development:
    username: "dmitrii"
    password: "admin"
    url: "jdbc:h2:mem:2"

  production:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_EXTERNAL_URL}
ebean:
  migration:
    run: true