-- apply changes
create table urlentity (
  id                            bigint generated by default as identity not null,
  created_at                    timestamptz not null,
  name                          varchar(255),
  constraint pk_urlentity primary key (id)
);

