-- apply changes
create table urlentity (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  created_at                    timestamp not null,
  constraint pk_urlentity primary key (id)
);

